## By default, SwiftLint uses a set of sensible default rules you can adjust:
#disabled_rules: # rule identifiers turned on by default to exclude from running
#  - colon
#  - comma
#  - control_statement
#opt_in_rules: # some rules are turned off by default, so you need to opt-in
#  - empty_count # Find all the available rules by running: `swiftlint rules`
#
## Alternatively, specify all rules explicitly by uncommenting this option:
## only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
##   - empty_parameters
##   - vertical_whitespace
#
#included: # paths to include during linting. `--path` is ignored if present.
#  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - build
  - BuildTools
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self

## configurable rules can be customized from this configuration file
## binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 450 # warning
  - 1000 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 2000
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
identifier_name:
  min_length: # only min_length
    error: 1 # only error
  validates_start_with_lowercase: false
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
  allowed_symbols: ["_"] # these are allowed in identifier names

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)


########
disabled_rules: # rule identifiers turned on by default to exclude from running
##    #  - line_length
##    - force_cast
###      - force_try
##    - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - shorthand_operator
  
#cyclomatic_complexity:
#    ignores_case_statements: true
#    warning: 50
##line_length:
##    warning: 185
##    ignores_function_declarations: true
##    ignores_comments: true
##    ignores_interpolated_strings: true
##    ignores_urls: true

